export interface CancerProstataPatients {
  message:   string;
  pacientes: Patient[];
}

export interface CancerProstataPatient {
  message:   string;
  paciente: Patient;
}

export interface Patient {
  id: string,
  dni: string,
  edad: string,
  etnia: string,
  cp: string,
  nombre: string,
  apellidos: string,
  telMovil: string,
  direccion: string,
  municipio: string,
  provincia: string,
  his: string,
  fechaCir: string,
  obesidad: string,
  hta: string,
  dm: string,
  erg: string,
  nbiopsia: string,
  tabaco: string,
  hereda: string,
  tactor: string,
  psapre: string,
  psalt: string,
  tdupre: string,
  ecotr: string,
  histo: string,
  gleason1: string,
  nclipos: string,
  bilat: string,
  porcent: string,
  iperin: string,
  ilinf: string,
  ivascu: string,
  tnm1: string,
  histo2: string,
  gleason2: string,
  bilat2: string,
  localiz: string,
  multifoc: string,
  volumen: string,
  extracap: string,
  vvss: string,
  iperin2: string,
  ilinf2: string,
  ivascu2: string,
  pinag: string,
  margen: string,
  tnm2: string,
  psapos: string,
  rtpadyu: string,
  rtpmes: string,
  rbq: string,
  trbq: string,
  tdupli: string,
  t1mtx: string,
  fechafin: string,
  fallec: string,
  tsuperv: string,
  tsegui: string,
  psafin: string,
  capra_s: string,
  ra1: string,
  ra2: string,
  pten: string,
  ki67: string,
  spink1: string,
  c_myc: string
}